apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: deployment
        imagePullPolicy: Always
        env:
        - name: ENV
          value: "prod"
        - name: production
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 500Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fib-app
spec:
  minReplicas: 3
  maxReplicas: 6

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fib-app
spec:
  tls:
  - hosts:
    - fib-app.prod.gt.com
    secretName: star.gt.com
  rules:
  - host: fib-app.prod.gt.com
    http:
      paths:
      - backend:
          service:
            name: fib-app
            port:
              number: 8000
        path: /
        pathType: Prefix
