apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: deployment
        imagePullPolicy: Always
        env:
        - name: ENV
          value: "dev"
        - name: production
          value: "false"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 100Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fib-app
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fib-app
spec:
  tls:
  - hosts:
    - fib-app.dev.gt.com
    secretName: star.gt.com
  rules:
  - host: fib-app.dev.gt.com
    http:
      paths:
      - backend:
          service:
            name: fib-app
            port:
              number: 8000
        path: /
        pathType: Prefix
