docker:build:
  stage: docker:build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/fib-app/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  only:
  - branches
  - tags
  - merge_request

docker:push:
  stage: docker:push
  extends:
  - docker:build
  variables:
    PUSH: "true"
