apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fib-app
  labels: {}
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fib-app
  targetCPUUtilizationPercentage: 80
