apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./rbac.yml
- ./deploy.yml
- ./svc.yml
- ./hpa.yml
- ./pdb.yml
- ./ingress.yml

images:
- name: registry.gitlab.com/gt-py-app/fib-app
