apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fib-app
  labels: {}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fib-app
      app.kubernetes.io/instance: fib-app
